[package]
name = "algos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbtree = "0.1"
serde = "1.0.147"
ciborium = "0.2.0"
rand = "0.8.5"
tempdir = "0.3.7"